theme: jekyll-theme-minimal

name:         Big Data in the Arts and Humanities
tagline:      Some Arts and Humanities Research Council Projects
baseurl: ""
show_downloads: true

collections:
        contributions:
                output: true
defaults:
        -
          scope:
                path: ""
                type: contributions

          values:
                layout: default
