name:         Big Data in the Arts and Humanities
tagline:      Some Arts and Humanities Research Council Projects
baseurl: "/BigDataBooklet"
show_downloads: true

collections:
        contributions:
                output: true
                defaults:
                        values:
                                layout: default
defaults:
          scope:
                path: ""
                type: contributions

          values:
                layout: default

theme: jekyll-theme-minimal
